### ISSUE TITLE
Bashio missing

### ISSUE THREAD

**Issue by PePeLLee** [ljsquare/hassio-addons#1]
I have installed fresh HA on debian11 on other hardware and reverted backup from old machine.
Want to be compliant with supervisor I don't run dockers on my own - only addons. I was using ispyagent previously so wanted to use you addon. I cannot start it due to missing dependency probably:

```s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
exec: fatal: unable to exec bashio
: No such file or directory
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

Could you provide me steps to install bashio or include it into your repo?

**Comment by PePeLLee** [comment]
It seems "run" file has DOS end of lines, when fixed it works fine.

**Comment by kgomez6** [comment]
how did you fixed this issue, like how did you edit it?

**Comment by PePeLLee** [comment]
You can exec bash inside container and then save modified container but in the end I'm not using this add-on. I have it run as simple docker container in other virtual machine

**Comment by ljsquare** [comment]
It should be fixed now with the new version.
