### ISSUE TITLE
Agent DVR: Installing FFmpeg 6 Complete! on opening webui

### ISSUE THREAD

**Issue by iVolt1** [ljsquare/hassio-addons#5]
Hi ljsquare,

I have installed the addon and when I open the web ui I only get the below web page.

![image](https://github.com/user-attachments/assets/005d7418-c4d7-4ec6-8f16-72fc713d9ada)

Is there a fix for that or something I can do?

Thanks,

iVolt1

**Comment by iVolt1** [comment]
Here is the latest log. Thanks.

-----------------------------------------------------------
 Add-on: iSpy Agent DVR
 iSpy is the world’s most popular open source video surveillance application. It's compatible with the the vast majority of consumer webcams and IP cameras.
-----------------------------------------------------------
 Add-on version: 0.93
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.1  (amd64 / generic-x86-64)
 Home Assistant Core: 2024.9.1
 Home Assistant Supervisor: 2024.09.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
[05:49:16] INFO: Configuring timezone (America/Chicago)...
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service base-addon-timezone successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started

**Comment by mgiamberardino** [comment]
@iVolt1 If you have some basic knowledge about shell and docker these are the steps I followed to get it working meanwhile the PR with the fix gets approved:

1. Install "Advanced SSH & Terminal" addon and disable the protection mode (Be carful since you could break your HA instance)
2. Restart this addon and before opening the web interface go to the Terminal addon and open the web interface.
3. Run `docker ps -f name=ispy -q`. This command will print the id of the docker container.
4. Run `docker exec -it CONTAINER_ID bash`. This will get you inside the docker container shell.
5. Run `apt install xz-utils`
6. Run `exit`
7. Now open the addon web interface.
8. DO NOT FORGET to enable the protection mode again in the Terminal & SSH addon.

This steps needs to be done every time you restart or rebuild the addon.

**Comment by iVolt1** [comment]
Thank you for the detailed instructions. Unfortunately, the addon still showed the exact same symptoms I posted above.

I stopped and rebuilt the addon and now the log is showing an error regarding /AgentDVR directory.  I noticed earlier that the addon referenced thing in the /Agent directory while the recent Ispy Agent DVR docker code I looked at showed references to the /AgentDVR directory so I wonder if there may be a disconnect there today.

 Add-on: iSpy Agent DVR
 iSpy is the world’s most popular open source video surveillance application. It's compatible with the the vast majority of consumer webcams and IP cameras.
-----------------------------------------------------------
 Add-on version: 0.93
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.1  (amd64 / generic-x86-64)
 Home Assistant Core: 2024.9.1
 Home Assistant Supervisor: 2024.09.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
[14:46:14] INFO: Configuring timezone (America/Chicago)...
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service base-addon-timezone successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
**/agent/run: line 5: cd: /agentDVR: No such file or directory**
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-timezone: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-timezone successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by ljsquare** [comment]
I've tested the PR from @mgiamberardino and merged it.
Thanks @mgiamberardino for the PR.

**Comment by iVolt1** [comment]
Your fix worked!  Thank you again.
